const teams = [
    //DEUTSCHLAND

    //Bundesliga Teams 2024/2025
    { name: "FC Bayern München", id: "bayern", short: "BAY", league: "Bundesliga", stadium: "Allianz Arena", strength: 90 },
    { name: "Bayer 04 Leverkusen", id: "leverkusen", short: "B04", league: "Bundesliga", stadium: "BayArena", strength: 89 },
    { name: "RB Leipzig", id: "leipzig", short: "RBL", league: "Bundesliga", stadium: "Red Bull Arena", strength: 85 },
    { name: "Borussia Dortmund", id: "dortmund", short: "BVB", league: "Bundesliga", stadium: "Signal Iduna Park", strength: 86 },
    { name: "Eintracht Frankfurt", id: "frankfurt", short: "SGE", league: "Bundesliga", stadium: "Deutsche Bank Park", strength: 83 },
    { name: "VfL Wolfsburg", id: "wolfsburg", short: "WOB", league: "Bundesliga", stadium: "Volkswagen Arena", strength: 82 },
    { name: "VfB Stuttgart", id: "stuttgart", short: "VfB", league: "Bundesliga", stadium: "Mercedes-Benz Arena", strength: 79 },
    { name: "Werder Bremen", id: "bremen", short: "SVW", league: "Bundesliga", stadium: "Weserstadion", strength: 79 },
    { name: "Union Berlin", id: "berlin", short: "FCU", league: "Bundesliga", stadium: "Stadion An der Alten Försterei", strength: 78 },
    { name: "Mönchengladbach", id: "gladbach", short: "BMG", league: "Bundesliga", stadium: "Borussia-Park", strength: 77 },
    { name: "1. FSV Mainz 05", id: "mainz", short: "M05", league: "Bundesliga", stadium: "MEWA Arena", strength: 78 },
    { name: "TSG Hoffenheim", id: "hoffenheim", short: "TSG", league: "Bundesliga", stadium: "PreZero Arena", strength: 74 },
    { name: "SC Freiburg", id: "freiburg", short: "SCF", league: "Bundesliga", stadium: "Europa-Park Stadion",  strength: 79 },
    { name: "FC Augsburg", id: "augsburg", short: "FCA", league: "Bundesliga", stadium: "WWK Arena", strength: 77 },
    { name: "VfL Bochum", id: "bochum", short: "BOC", league: "Bundesliga", stadium: "Vonovia Ruhrstadion", strength: 71 },
    { name: "St. Pauli", id: "pauli", short: "STP", league: "Bundesliga", stadium: "Millerntor-Stadion", strength: 72 },
    { name: "FC Heidenheim", id: "heidenheim", short: "FCH", league: "Bundesliga", stadium: "Voith-Arena", strength: 72 },
    { name: "Holstein Kiel", id: "kiel", short: "KIE", league: "Bundesliga", stadium: "Holstein-Stadion", strength: 66 },

    //2_Bundesliga Teams 2024/2025
    { name: "Eintracht Braunschweig", id: "braunschweig", short: "EBS", league: "2_Bundesliga", stadium: "Eintracht-Stadion", strength: 67 },
    { name: "1. FC Köln", id: "koeln", short: "KOE", league: "2_Bundesliga", stadium: "RheinEnergieStadion", strength: 75 },
    { name: "Darmstadt 98", id: "darmstadt", short: "DAR", league: "2_Bundesliga", stadium: "Merck-Stadion am Böllenfalltor", strength: 69 },
    { name: "SV Elversberg", id: "elversberg", short: "ELV", league: "2_Bundesliga", stadium: "Waldstadion an der Kaiserlinde", strength: 69 },
    { name: "Fortuna Düsseldorf", id: "duesseldorf", short: "DU", league: "2_Bundesliga", stadium: "Merkur Spiel-Arena", strength: 70 },
    { name: "Greuther Fürth", id: "fuerth", short: "FUE", league: "2_Bundesliga", stadium: "Sportpark Ronhof Thomas Sommer", strength: 68 },
    { name: "Hamburger SV", id: "hamburg", short: "HSV", league: "2_Bundesliga", stadium: "Volksparkstadion", strength: 73 },
    { name: "Hannover 96", id: "hannover", short: "HAN", league: "2_Bundesliga", stadium: "Heinz-von-Heiden-Arena", strength: 70 },
    { name: "Hertha BSC", id: "hertha", short: "BSC", league: "2_Bundesliga", stadium: "Olympiastadion", strength: 69 },
    { name: "Jahn Regensburg", id: "regensburg", short: "REG", league: "2_Bundesliga", stadium: "Jahnstadion Regensburg", strength: 64 },
    { name: "1. FC Kaiserslautern", id: "kaiserslautern", short: "KAI", league: "2_Bundesliga", stadium: "Fritz-Walter-Stadion", strength: 70 },
    { name: "Karlsruher SC", id: "karlsruhe", short: "KSC", league: "2_Bundesliga", stadium: "Wildparkstadion", strength: 69 },
    { name: "1. FC Magdeburg", id: "magdeburg", short: "MAG", league: "2_Bundesliga", stadium: "MDCC-Arena", strength: 69 },
    { name: "1. FC Nürnberg", id: "nuernberg", short: "NUE", league: "2_Bundesliga", stadium: "Max-Morlock-Stadion", strength: 70 },
    { name: "SC Paderborn 07", id: "paderborn", short: "PAD", league: "2_Bundesliga", stadium: "Home Deluxe Arena", strength: 69 },
    { name: "Preußen Münster", id: "muenster", short: "MUE", league: "2_Bundesliga", stadium: "Preußenstadion", strength: 65 },
    { name: "Schalke 04", id: "schalke", short: "S04", league: "2_Bundesliga", stadium: "Veltins-Arena", strength: 69 },
    { name: "SSV Ulm 1846", id: "ulm", short: "ULM", league: "2_Bundesliga", stadium: "Donaustadion", strength: 65 },

    //3_Liga Teams 2024/2025
    { name: "FC Hansa Rostock", id: "rostock", short: "HRO", league: "3_Liga", stadium: "Kieler Str. 2", strength: 58 },
    { name: "VfL Osnabrück", id: "osnabrueck", short: "OSN", league: "3_Liga", stadium: "Bremer Brücke", strength: 53 },
    { name: "SV Wehen Wiesbaden", id: "wiesbaden", short: "WW", league: "3_Liga", stadium: "Brita-Arena", strength: 55 },
    { name: "Arminia Bielefeld", id: "bielefeld", short: "BIE", league: "3_Liga", stadium: "SchücoArena", strength: 58 },
    { name: "SV Sandhausen", id: "sandhausen", short: "SVS", league: "3_Liga", stadium: "Hardtwaldstadion", strength: 54 },
    { name: "SG Dynamo Dresden", id: "dresden", short: "SGD", league: "3_Liga", stadium: "Rudolf-Harbig-Stadion", strength: 60 },
    { name: "FC Erzgebirge Aue", id: "aue", short: "AUE", league: "3_Liga", stadium: "Erzgebirgsstadion", strength: 54 },
    { name: "FC Ingolstadt", id: "ingolstadt", short: "ING", league: "3_Liga", stadium: "Audi Sportpark", strength: 57 },
    { name: "TSV 1860 München", id: "1860muenchen", short: "M60", league: "3_Liga", stadium: "Grünwalder Stadion", strength: 56 },
    { name: "1. FC Saarbrücken", id: "saarbruecken", short: "SAA", league: "3_Liga", stadium: "Ludwigsparkstadion", strength: 60 },
    { name: "SC Verl", id: "verl", short: "VER", league: "3_Liga", stadium: "Sportclub-Arena", strength: 56 },
    { name: "SV Waldhof Mannheim", id: "mannheim", short: "SWM", league: "3_Liga", stadium: "Carl-Benz-Stadion", strength: 54 },
    { name: "FC Viktoria Köln", id: "viktoria", short: "VIK", league: "3_Liga", stadium: "Sportpark Höhenberg", strength: 56 },
    { name: "Borussia Dortmund II", id: "dortmund2", short: "BVBII", league: "3_Liga", stadium: "Stadion Rote Erde", strength: 54 },
    { name: "Rot Weiss Essen", id: "rwessen", short: "RWE", league: "3_Liga", stadium: "Stadion an der Hafenstraße", strength: 52 },
    { name: "SpVgg Unterhaching", id: "unterhaching", short: "UHA", league: "3_Liga", stadium: "Alpenbauer Sportpark", strength: 50 },
    { name: "Alemannia Aachen", id: "aachen", short: "AAC", league: "3_Liga", stadium: "Tivoli", strength: 56 },
    { name: "FC Energie Cottbus", id: "cottbus", short: "COT", league: "3_Liga", stadium: "Stadion der Freundschaft", strength: 53 },
    { name: "VfB Stuttgart II", id: "stuttgart2", short: "VFBII", league: "3_Liga", stadium: "Gazi-Stadion auf der Waldau", strength: 50 },
    { name: "Hannover 96 II", id: "hannover962", short: "H96II", league: "3_Liga", stadium: "Eilenriedestadion", strength: 52 },
    

    // ENGLAND

    //Premier_League Saison 2024/2025
    { name: "Arsenal", id: "arsenal", short: "ARS", league: "Premier_League", stadium: "Emirates Stadium", strength: 88 },
    { name: "Aston Villa", id: "astonvilla", short: "AVL", league: "Premier_League", stadium: "Villa Park", strength: 80 },
    { name: "AFC Bournemouth", id: "bournemouth", short: "BOU", league: "Premier_League", stadium: "Vitality Stadium", strength: 75 },
    { name: "Brentford", id: "brentford", short: "BRE", league: "Premier_League", stadium: "Gtech Community Stadium", strength: 78 },
    { name: "Brighton & Hove Albion", id: "brighton", short: "BHA", league: "Premier_League", stadium: "Amex Stadium", strength: 80 },
    { name: "Chelsea", id: "chelsea", short: "CHE", league: "Premier_League", stadium: "Stamford Bridge", strength: 87 },
    { name: "Crystal Palace", id: "crystalpalace", short: "CRY", league: "Premier_League", stadium: "Selhurst Park", strength: 77 },
    { name: "Everton", id: "everton", short: "EVE", league: "Premier_League", stadium: "Goodison Park", strength: 79 },
    { name: "Fulham", id: "fulham", short: "FUL", league: "Premier_League", stadium: "Craven Cottage", strength: 76 },
    { name: "Ipswich Town", id: "ipswich", short: "IPS", league: "Premier_League", stadium: "Portman Road", strength: 72 },
    { name: "Leicester City", id: "leicester", short: "LEI", league: "Premier_League", stadium: "King Power Stadium", strength: 75 },
    { name: "Liverpool", id: "liverpool", short: "LIV", league: "Premier_League", stadium: "Anfield", strength: 90 },
    { name: "Manchester City", id: "mancity", short: "MCI", league: "Premier_League", stadium: "Etihad Stadium", strength: 88 },
    { name: "Manchester United", id: "manunited", short: "MUN", league: "Premier_League", stadium: "Old Trafford", strength: 86 },
    { name: "Newcastle United", id: "newcastle", short: "NEW", league: "Premier_League", stadium: "St James' Park", strength: 84 },
    { name: "Nottingham Forest", id: "nottingham", short: "NFO", league: "Premier_League", stadium: "City Ground", strength: 78 },
    { name: "Southampton", id: "southampton", short: "SOU", league: "Premier_League", stadium: "St Mary's Stadium", strength: 73 },
    { name: "Tottenham Hotspur", id: "tottenham", short: "TOT", league: "Premier_League", stadium: "Tottenham Hotspur Stadium", strength: 84 },
    { name: "West Ham United", id: "westham", short: "WHU", league: "Premier_League", stadium: "London Stadium", strength: 80 },
    { name: "Wolverhampton Wanderers", id: "wolves", short: "WOL", league: "Premier_League", stadium: "Molineux Stadium", strength: 78 },

    //EFL Championship Saison 2024/2025
    { name: "Blackburn Rovers",     id: "blackburnrovers",       short: "BKR", league: "Championship", stadium: "Ewood Park",                   strength: 73 },
    { name: "Bristol City",         id: "bristolcity",           short: "BRC", league: "Championship", stadium: "Ashton Gate Stadium",          strength: 71 },
    { name: "FC Burnley",           id: "burnley",               short: "BRN", league: "Championship", stadium: "Turf Moor",                    strength: 72 },
    { name: "Cardiff City",         id: "cardiffcity",           short: "CDF", league: "Championship", stadium: "Cardiff City Stadium",         strength: 74 },
    { name: "Coventry City",        id: "coventrycity",          short: "COV", league: "Championship", stadium: "Coventry Building Society Arena", strength: 75 },
    { name: "Derby County",         id: "derbycounty",           short: "DER", league: "Championship", stadium: "Pride Park Stadium",           strength: 76 },
    { name: "Hull City",            id: "hullcity",              short: "HUL", league: "Championship", stadium: "MKM Stadium",                  strength: 73 },
    { name: "Leeds United",         id: "leedsunited",           short: "LED", league: "Championship", stadium: "Elland Road",                  strength: 78 },
    { name: "Luton Town",           id: "lutontown",             short: "LUT", league: "Championship", stadium: "Kenilworth Road",              strength: 66 },
    { name: "FC Middlesbrough",     id: "middlesbrough",         short: "MID", league: "Championship", stadium: "Riverside Stadium",            strength: 77 },
    { name: "FC Millwall",          id: "millwall",              short: "MIL", league: "Championship", stadium: "The Den",                      strength: 68 },
    { name: "Norwich City",         id: "norwichcity",           short: "NOR", league: "Championship", stadium: "Carrow Road",                  strength: 70 },
    { name: "Oxford United",        id: "oxfordunited",          short: "OXF", league: "Championship", stadium: "Kassam Stadium",               strength: 62 },
    { name: "Plymouth Argyle",      id: "plymouthargyle",        short: "PLY", league: "Championship", stadium: "Home Park",                    strength: 60 },
    { name: "FC Portsmouth",        id: "portsmouth",            short: "POR", league: "Championship", stadium: "Fratton Park",                 strength: 70 },
    { name: "Preston North End",    id: "preston_northend",      short: "PRE", league: "Championship", stadium: "Deepdale",                     strength: 68 },
    { name: "Queens Park Rangers",  id: "qpr",                   short: "QPR", league: "Championship", stadium: "Matrade Loftus Road Stadium",  strength: 72 },
    { name: "Sheffield United",     id: "sheffieldunited",       short: "SHU", league: "Championship", stadium: "Bramall Lane",                 strength: 75 },
    { name: "Sheffield Wednesday",  id: "sheffieldwednesday",    short: "SHW", league: "Championship", stadium: "Hillsborough Stadium",         strength: 74 },
    { name: "Stoke City",           id: "stokecity",             short: "STK", league: "Championship", stadium: "Bet365 Stadium",               strength: 68 },
    { name: "AFC Sunderland",       id: "sunderland",            short: "SUN", league: "Championship", stadium: "Stadium of Light",             strength: 78 },
    { name: "Swansea City",         id: "swanseacity",           short: "SWA", league: "Championship", stadium: "Swansea.com Stadium",          strength: 66 },
    { name: "FC Watford",           id: "watford",               short: "WAT", league: "Championship", stadium: "Vicarage Road",                strength: 70 },
    { name: "West Bromwich Albion", id: "westbromwichalbion",    short: "WBA", league: "Championship", stadium: "The Hawthorns",                strength: 72 },
  
  

    // EFL EFL_LeagueOne Saison 2024/2025
    { name: "FC Barnsley",          id: "barnsley",             short: "BLY", league: "EFL_LeagueOne", stadium: "Oakwell Stadium",             strength: 70 },
    { name: "Birmingham City",      id: "birminghamcity",       short: "BIR", league: "EFL_LeagueOne", stadium: "St. Andrew’s Trillion Trophy Stadium", strength: 72 },
    { name: "FC Blackpool",         id: "blackpool",            short: "BKP", league: "EFL_LeagueOne", stadium: "Bloomfield Road",            strength: 69 },
    { name: "Bolton Wanderers",     id: "boltonwanderers",      short: "BWA", league: "EFL_LeagueOne", stadium: "University of Bolton Stadium", strength: 71 },
    { name: "Bristol Rovers",       id: "bristolrovers",        short: "BRR", league: "EFL_LeagueOne", stadium: "Memorial Stadium",           strength: 67 },
    { name: "Burton Albion",        id: "burtonalbion",         short: "BUR", league: "EFL_LeagueOne", stadium: "Pirelli Stadium",            strength: 61 },
    { name: "Cambridge United",     id: "cambridgeunited",      short: "CAM", league: "EFL_LeagueOne", stadium: "Abbey Stadium",              strength: 62 },
    { name: "Charlton Athletic",    id: "charltonathletic",     short: "CHA", league: "EFL_LeagueOne", stadium: "The Valley",                 strength: 70 },
    { name: "Crawley Town",         id: "crawleytown",          short: "CRA", league: "EFL_LeagueOne", stadium: "Broadfield Stadium",         strength: 58 },
    { name: "Exeter City",          id: "exetercity",           short: "EXT", league: "EFL_LeagueOne", stadium: "St. James’ Park",            strength: 64 },
    { name: "Huddersfield Town",    id: "huddersfieldtown",     short: "HUD", league: "EFL_LeagueOne", stadium: "John Smith’s Stadium",       strength: 73 },
    { name: "Leyton Orient",        id: "leytonorient",         short: "LEY", league: "EFL_LeagueOne", stadium: "Brisbane Road",              strength: 61 },
    { name: "Lincoln City",         id: "lincolncity",          short: "LIN", league: "EFL_LeagueOne", stadium: "LNER Stadium",               strength: 65 },
    { name: "Mansfield Town",       id: "mansfieldtown",        short: "MAN", league: "EFL_LeagueOne", stadium: "One Call Stadium",           strength: 62 },
    { name: "Northampton Town",     id: "northamptontown",      short: "NOR", league: "EFL_LeagueOne", stadium: "Sixfields Stadium",          strength: 63 },
    { name: "Peterborough United",  id: "peterboroughunited",   short: "PET", league: "EFL_LeagueOne", stadium: "Weston Homes Stadium",       strength: 68 },
    { name: "FC Reading",           id: "reading",              short: "REA", league: "EFL_LeagueOne", stadium: "Madejski Stadium",           strength: 70 },
    { name: "Rotherham United",     id: "rotherhamunited",      short: "ROH", league: "EFL_LeagueOne", stadium: "New York Stadium",           strength: 69 },
    { name: "Shrewsbury Town",      id: "shrewsburytown",       short: "SHR", league: "EFL_LeagueOne", stadium: "Montgomery Waters Meadow",   strength: 66 },
    { name: "FC Stevenage",         id: "stevenage",            short: "STE", league: "EFL_LeagueOne", stadium: "Broadhall Way",             strength: 62 },
    { name: "Stockport County",     id: "stockportcounty",      short: "STO", league: "EFL_LeagueOne", stadium: "Edgeley Park",               strength: 64 },
    { name: "Wigan Athletic",       id: "wiganathletic",        short: "WIG", league: "EFL_LeagueOne", stadium: "The Brick Community Stadium", strength: 70 },
    { name: "AFC Wrexham",          id: "wrexham",              short: "WRX", league: "EFL_LeagueOne", stadium: "Racecourse Ground",          strength: 67 },
    { name: "Wycombe Wanderers",    id: "wycombewanderers",     short: "WYC", league: "EFL_LeagueOne", stadium: "Adams Park",                 strength: 65 },
  
  


    //Niederlande

    //Eredivisie Saison 2024/2025
    { name: "Ajax Amsterdam", id: "ajax", short: "AJA", league: "Eredivisie", stadium: "Johan Cruijff Arena", strength: 82 },
    { name: "AZ Alkmaar", id: "azalkmaar", short: "AZ", league: "Eredivisie", stadium: "AFAS Stadion", strength: 80 },
    { name: "Feyenoord Rotterdam", id: "feyenoord", short: "FEY", league: "Eredivisie", stadium: "De Kuip", strength: 83 },
    { name: "PSV Eindhoven", id: "psv", short: "PSV", league: "Eredivisie", stadium: "Philips Stadion", strength: 84 },
    { name: "FC Utrecht", id: "utrecht", short: "UTR", league: "Eredivisie", stadium: "Stadion Galgenwaard", strength: 78 },
    { name: "FC Twente", id: "fctwente", short: "TWE", league: "Eredivisie", stadium: "De Grolsch Veste", strength: 79 },
    { name: "SC Heerenveen", id: "heerenveen", short: "HEE", league: "Eredivisie", stadium: "Abe Lenstra Stadion", strength: 76 },
    { name: "NAC Breda", id: "breda", short: "NAC", league: "Eredivisie", stadium: "Rat-Verlegh-Stadion", strength: 69 },
    { name: "FC Groningen", id: "groningen", short: "GRO", league: "Eredivisie", stadium: "Euroborg", strength: 75 },
    { name: "Sparta Rotterdam", id: "sparta", short: "SPA", league: "Eredivisie", stadium: "Het Kasteel", strength: 74 },
    { name: "Willem II Tilburg", id: "willem", short: "WIL", league: "Eredivisie", stadium: "Koning Willem II Stadion", strength: 73 },
    { name: "Heracles Almelo", id: "heracles", short: "HER", league: "Eredivisie", stadium: "Erve Asito", strength: 72 },
    { name: "Go Ahead Eagles", id: "eagles", short: "GAE", league: "Eredivisie", stadium: "De Adelaarshorst", strength: 71 },
    { name: "PEC Zwolle", id: "pec", short: "PEC", league: "Eredivisie", stadium: "MAC³PARK Stadion", strength: 70 },
    { name: "RKC Waalwijk", id: "rkc", short: "RKC", league: "Eredivisie", stadium: "Mandemakers Stadion", strength: 69 },
    { name: "Fortuna Sittard", id: "fortuna", short: "FOR", league: "Eredivisie", stadium: "Fortuna Sittard Stadion", strength: 68 },
    { name: "NEC Nijmegen", id: "nec", short: "NEC", league: "Eredivisie", stadium: "Goffertstadion", strength: 67 },
    { name: "Almere City FC", id: "almere", short: "AMC", league: "Eredivisie", stadium: "Yanmar Stadion", strength: 66 },
    
    //Eerste_Divisie 2024/2025
    { name: "ADO Den Haag",        id: "adodenhaag",        short: "ADO", league: "Eerste_Divisie", stadium: "Bingoal Stadion",        strength: 70 },
    { name: "Jong Ajax",           id: "jongajax",          short: "JJA", league: "Eerste_Divisie", stadium: "Sportpark De Toekomst", strength: 62 },
    { name: "Jong AZ",             id: "jongaz",            short: "JAZ", league: "Eerste_Divisie", stadium: "AFAS Trainingscomplex", strength: 63 },
    { name: "De Graafschap",       id: "degraafschap",      short: "GRF", league: "Eerste_Divisie", stadium: "Stadion De Vijverberg", strength: 70 },
    { name: "FC Den Bosch",        id: "fcdendbosch",       short: "DEN", league: "Eerste_Divisie", stadium: "Stadion De Vliert",     strength: 68 },
    { name: "SC Cambuur",          id: "sccambuur",         short: "SCC", league: "Eerste_Divisie", stadium: "Kooi Stadion",          strength: 69 },
    { name: "FC Emmen",            id: "fcemmen",           short: "EMM", league: "Eerste_Divisie", stadium: "De Oude Meerdijk",     strength: 65 },
    { name: "FC Dordrecht",        id: "fcdordrecht",       short: "DOR", league: "Eerste_Divisie", stadium: "M-Scores Stadion",     strength: 58 },
    { name: "FC Eindhoven",        id: "fceindhoven",       short: "EIN", league: "Eerste_Divisie", stadium: "Jan-Louwers-Stadion",  strength: 60 },
    { name: "Excelsior Rotterdam", id: "excelsiorrotterdam", short: "EXC", league: "Eerste_Divisie", stadium: "Van Donge & De Roo Stadion", strength: 64 },
    { name: "Helmond Sport",       id: "helmondsport",      short: "HEL", league: "Eerste_Divisie", stadium: "GS Staalwerken Stadion", strength: 57 },
    { name: "MVV Maastricht",      id: "mvvmaastricht",     short: "MVV", league: "Eerste_Divisie", stadium: "Stadion De Geusselt",  strength: 62 },
    { name: "Jong PSV",            id: "jongpsv",           short: "JPS", league: "Eerste_Divisie", stadium: "PSV Campus De Herdgang", strength: 60 },
    { name: "Roda JC Kerkrade",    id: "rodajc",            short: "RJC", league: "Eerste_Divisie", stadium: "Parkstad Limburg Stadion", strength: 71 },
    { name: "Telstar Velsen",      id: "telstarvelsen",     short: "TEL", league: "Eerste_Divisie", stadium: "711 Stadion",           strength: 55 },
    { name: "TOP Oss",             id: "toposs",            short: "OSS", league: "Eerste_Divisie", stadium: "Frans-Heesen-Stadion", strength: 60 },
    { name: "Jong FC Utrecht",     id: "jongutrecht",     short: "JFC", league: "Eerste_Divisie", stadium: "Sportcomplex Zoudenbalch", strength: 62 },
    { name: "Vitesse Arnheim",     id: "vitesse",    short: "VIT", league: "Eerste_Divisie", stadium: "GelreDome",            strength: 72 },
    { name: "FC Volendam",         id: "fcvolendam",        short: "VOL", league: "Eerste_Divisie", stadium: "Kras Stadion",         strength: 66 },
    { name: "VVV-Venlo",           id: "vvvvenlo",          short: "VVV", league: "Eerste_Divisie", stadium: "De Koel",             strength: 68 },

    //Italien

    //Serie_A (2024/2025)
    { name: "Atalanta Bergamo", id: "atalanta", short: "ATA", league: "Serie_A", stadium: "Gewiss Stadium", strength: 82 },
    { name: "Bologna FC", id: "bologna", short: "BOL", league: "Serie_A", stadium: "Stadio Renato Dall'Ara", strength: 78 },
    { name: "Cagliari Calcio", id: "cagliari", short: "CAG", league: "Serie_A", stadium: "Unipol Domus", strength: 75 },
    { name: "Como 1907", id: "como", short: "COM", league: "Serie_A", stadium: "Stadio Giuseppe Sinigaglia", strength: 70 },
    { name: "Empoli FC", id: "empoli", short: "EMP", league: "Serie_A", stadium: "Stadio Carlo Castellani", strength: 72 },
    { name: "ACF Fiorentina", id: "fiorentina", short: "FIO", league: "Serie_A", stadium: "Stadio Artemio Franchi", strength: 80 },
    { name: "Genoa CFC", id: "genoa", short: "GEN", league: "Serie_A", stadium: "Stadio Luigi Ferraris", strength: 74 },
    { name: "Hellas Verona FC", id: "verona", short: "VFC", league: "Serie_A", stadium: "Stadio Marcantonio Bentegodi", strength: 73 },
    { name: "Inter Mailand", id: "inter", short: "INT", league: "Serie_A", stadium: "San Siro", strength: 88 },
    { name: "Juventus Turin", id: "juventus", short: "JUV", league: "Serie_A", stadium: "Juventus Stadium", strength: 86 },
    { name: "Lazio Rom", id: "laziorom", short: "LAZ", league: "Serie_A", stadium: "Stadio Olimpico", strength: 84 },
    { name: "US Lecce", id: "lecce", short: "LEC", league: "Serie_A", stadium: "Stadio Via del Mare", strength: 71 },
    { name: "AC Mailand", id: "milan", short: "ACM", league: "Serie_A", stadium: "San Siro", strength: 87 },
    { name: "AC Monza", id: "monza", short: "MON", league: "Serie_A", stadium: "Stadio Brianteo", strength: 76 },
    { name: "SSC Neapel", id: "napoli", short: "NAP", league: "Serie_A", stadium: "Stadio Diego Armando Maradona", strength: 85 },
    { name: "Parma Calcio", id: "parma", short: "PMA", league: "Serie_A", stadium: "Stadio Ennio Tardini", strength: 73 },
    { name: "AS Rom", id: "asrom", short: "ASR", league: "Serie_A", stadium: "Stadio Olimpico", strength: 77 },
    { name: "FC Turin", id: "fcturin", short: "TUR", league: "Serie_A", stadium: "Stadio Olimpico Grande Torino", strength: 73 },
    { name: "Venezia", id: "venezia", short: "VEN", league: "Serie_A", stadium: "Stadio Pier Luigi Penzo", strength: 70 },
    { name: "Udinese Calcio", id: "udinese", short: "UDI", league: "Serie_A", stadium: "Bluenergy Stadium", strength: 69 },

    //Serie_B Saison 2024/2025
    { name: "Frosinone Calcio",      id: "frosinonecalcio",      short: "FRO", league: "Serie_B", stadium: "PSC Arena",                     strength: 70 },
    { name: "US Sassuolo Calcio",    id: "ussassuolocalcio",    short: "SAS", league: "Serie_B", stadium: "Mapei Stadium – Città del Tricolore", strength: 72 },
    { name: "US Salernitana",        id: "ussalernitana",        short: "SAL", league: "Serie_B", stadium: "Stadio Arechi",                   strength: 69 },
    { name: "US Cremonese",          id: "uscremonese",          short: "CRE", league: "Serie_B", stadium: "Stadio Giovanni Zini",            strength: 74 },
    { name: "US Catanzaro 1929",     id: "uscatanzaro",          short: "CAT", league: "Serie_B", stadium: "Stadio Nicola Ceravolo",         strength: 70 },
    { name: "FC Palermo",            id: "fcpalermo",            short: "PAL", league: "Serie_B", stadium: "Stadio Renzo Barbera",           strength: 76 },
    { name: "Sampdoria Genua",       id: "sampdoriagenua",       short: "SAM", league: "Serie_B", stadium: "Stadio Luigi Ferraris",          strength: 78 },
    { name: "Brescia Calcio",        id: "brescacalcio",         short: "BRES", league: "Serie_B", stadium: "Stadio Mario Rigamonti",         strength: 71 },
    { name: "Cosenza Calcio",        id: "cosenza",              short: "COS", league: "Serie_B", stadium: "Stadio San Vito – Gigi Marulla", strength: 68 },
    { name: "FC Modena",             id: "fcmodena",             short: "MOD", league: "Serie_B", stadium: "Stadio Alberto Braglia",         strength: 69 },
    { name: "AC Reggiana",           id: "acreggiana",           short: "ACR", league: "Serie_B", stadium: "Mapei Stadium – Città del Tricolore", strength: 67 },
    { name: "FC Südtirol",           id: "fcsudtirol",           short: "SUD", league: "Serie_B", stadium: "Drusus-Stadion",                  strength: 66 },
    { name: "Pisa Sporting Club",    id: "pisasportingclub",     short: "PIS", league: "Serie_B", stadium: "Stadio Arena Garibaldi – Romeo Anconetani", strength: 67 },
    { name: "AS Cittadella",         id: "ascittadella",         short: "CIT", league: "Serie_B", stadium: "Stadio Pier Cesare Tombolato",   strength: 66 },
    { name: "Spezia Calcio",         id: "spezia",               short: "SPE", league: "Serie_B", stadium: "Stadio Alberto Picco",           strength: 74 },
    { name: "SSC Bari",              id: "sscbari",              short: "BRI", league: "Serie_B", stadium: "Stadio San Nicola",              strength: 72 },
    { name: "Mantova 1911",          id: "mantova1911",          short: "MNV", league: "Serie_B", stadium: "Stadio Danilo Martelli",          strength: 60 },
    { name: "FC Cesena",             id: "fccesena",             short: "CES", league: "Serie_B", stadium: "Stadio Dino Manuzzi",            strength: 62 },
    { name: "SS Juve Stabia",        id: "ssjuvestabia",         short: "SSJ", league: "Serie_B", stadium: "Stadio Romeo Menti",             strength: 61 },
    { name: "Carrarese Calcio",      id: "carrarescalcio",       short: "CAR", league: "Serie_B", stadium: "Stadio dei Marmi",               strength: 59 },

    //Spanien

    //LaLiga Saison 2024/2025
    { name: "Deportivo Alavés", id: "alaves", short: "ALA", league: "La_Liga", stadium: "Mendizorrotza", strength: 70 },
    { name: "Athletic Bilbao", id: "athletic", short: "ATH", league: "La_Liga", stadium: "San Mamés", strength: 75 },
    { name: "Atlético Madrid", id: "atletico", short: "ATM", league: "La_Liga", stadium: "Cívitas Metropolitano", strength: 85 },
    { name: "FC Barcelona", id: "barcelona", short: "BAR", league: "La_Liga", stadium: "Estadi Olímpic Lluís Companys", strength: 88 },
    { name: "Celta Vigo", id: "celta", short: "CEL", league: "La_Liga", stadium: "Abanca-Balaídos", strength: 72 },
    { name: "RCD Espanyol", id: "espanyol", short: "ESP", league: "La_Liga", stadium: "RCDE Stadium", strength: 70 },
    { name: "Getafe CF", id: "getafe", short: "GET", league: "La_Liga", stadium: "Coliseum Alfonso Pérez", strength: 71 },
    { name: "Girona FC", id: "girona", short: "GIR", league: "La_Liga", stadium: "Montilivi", strength: 69 },
    { name: "UD Las Palmas", id: "laspalmas", short: "LPA", league: "La_Liga", stadium: "Estadio de Gran Canaria", strength: 67 },
    { name: "CD Leganés", id: "leganes", short: "LEG", league: "La_Liga", stadium: "Butarque", strength: 66 },
    { name: "RCD Mallorca", id: "mallorca", short: "MAL", league: "La_Liga", stadium: "Son Moix", strength: 70 },
    { name: "CA Osasuna", id: "osasuna", short: "OSA", league: "La_Liga", stadium: "Reyno de Navarra", strength: 73 },
    { name: "Rayo Vallecano", id: "rayo", short: "RAY", league: "La_Liga", stadium: "Estadio de Vallecas", strength: 71 },
    { name: "Real Betis", id: "realbetis", short: "BET", league: "La_Liga", stadium: "Benito Villamarín", strength: 74 },
    { name: "Real Madrid", id: "realmadrid", short: "RMD", league: "La_Liga", stadium: "Santiago Bernabéu", strength: 90 },
    { name: "Real Sociedad", id: "realsociedad", short: "RSO", league: "La_Liga", stadium: "Reale Arena", strength: 78 },
    { name: "Sevilla FC", id: "sevilla", short: "SEV", league: "La_Liga", stadium: "Ramón Sánchez Pizjuán", strength: 76 },
    { name: "Valencia CF", id: "valencia", short: "VAL", league: "La_Liga", stadium: "Mestalla", strength: 72 },
    { name: "Real Valladolid", id: "valladolid", short: "VLL", league: "La_Liga", stadium: "José Zorrilla", strength: 69 },
    { name: "Villarreal CF", id: "villarreal", short: "VIL", league: "La_Liga", stadium: "Estadio de la Cerámica", strength: 77 },

    // LaLiga 2 Saison 2024/2025

    { name: "Albacete Balompié",    id: "albacetebalompie",    short: "ALB", league: "La_Liga2", stadium: "Estadio Carlos Belmonte",    strength: 65 },
    { name: "UD Almería",           id: "udalmeria",           short: "ALM", league: "La_Liga2", stadium: "Estadio de los Juegos Mediterráneos", strength: 72 },
    { name: "CD Castellón",         id: "cdcastellon",         short: "CAS", league: "La_Liga2", stadium: "Nou Castalia",              strength: 60 },
    { name: "Deportivo La Coruña",  id: "deportivolacoruna",   short: "DEP", league: "La_Liga2", stadium: "Estadio Riazor",            strength: 75 },
    { name: "Real Oviedo",          id: "realoviedo",          short: "OVI", league: "La_Liga2", stadium: "Estadio Nuevo Carlos Tartiere", strength: 71 },
    { name: "Burgos CF",            id: "burgoscf",            short: "BCF", league: "La_Liga2", stadium: "Estadio Municipal de El Plantío", strength: 63 },
    { name: "FC Cádiz",             id: "fccadiz",             short: "CAD", league: "La_Liga2", stadium: "Estadio Nuevo Mirandilla",   strength: 74 },
    { name: "FC Cartagena",         id: "fccartagena",         short: "FCC", league: "La_Liga2", stadium: "Estadio Cartagonova",         strength: 67 },
    { name: "SD Eibar",             id: "sdeibar",             short: "EIB", league: "La_Liga2", stadium: "Estadio Municipal de Ipurua", strength: 70 },
    { name: "FC Elche",             id: "fcelche",             short: "ELC", league: "La_Liga2", stadium: "Estadio Manuel Martínez Valero", strength: 77 },
    { name: "CD Eldense",           id: "cdeldense",           short: "ELD", league: "La_Liga2", stadium: "Estadio Municipal Nuevo Pepico Amat", strength: 58 },
    { name: "Racing de Ferrol",     id: "racingdeferrol",      short: "RAF", league: "La_Liga2", stadium: "Estadio Municipal de A Malata", strength: 60 },
    { name: "Sporting Gijón",       id: "sportinggijon",       short: "GIJ", league: "La_Liga2", stadium: "Estadio Municipal El Molinón", strength: 73 },
    { name: "FC Granada",           id: "fcgranada",           short: "GRA", league: "La_Liga2", stadium: "Estadio Nuevo Los Cármenes", strength: 74 },
    { name: "SD Huesca",            id: "sdhuesca",            short: "HUE", league: "La_Liga2", stadium: "Estadio El Alcoraz",         strength: 71 },
    { name: "UD Levante",           id: "udlevante",           short: "LEV", league: "La_Liga2", stadium: "Estadio Ciudad de Valencia", strength: 76 },
    { name: "FC Málaga",            id: "fcmalaga",            short: "MLG", league: "La_Liga2", stadium: "Estadio La Rosaleda",        strength: 73 },
    { name: "CD Mirandés",          id: "cdmirandes",          short: "MIR", league: "La_Liga2", stadium: "Estadio Municipal de Anduva", strength: 62 },
    { name: "FC Córdoba",           id: "fccordoba",           short: "COR", league: "La_Liga2", stadium: "Estadio Nuevo Arcángel",     strength: 68 },
    { name: "Racing Santander",     id: "racingsantander",     short: "SAN", league: "La_Liga2", stadium: "Campos de Sport de El Sardinero", strength: 69 },
    { name: "Real Saragossa",       id: "realsaragossa",       short: "SAR", league: "La_Liga2", stadium: "Estadio La Romareda",        strength: 77 },
    { name: "CD Teneriffa",         id: "cdteneriffa",         short: "TEN", league: "La_Liga2", stadium: "Estadio Heliodoro Rodríguez López", strength: 70 },
  
  


    // Frankreich

    // Ligue 1 Saison 2024/2025

    { name: "Paris Saint-Germain", id: "psg", short: "PSG", league: "Ligue_1", stadium: "Parc des Princes", strength: 90 },
    { name: "AS Monaco", id: "monaco", short: "ASM", league: "Ligue_1", stadium: "Stade Louis II", strength: 80 },
    { name: "Stade Brest", id: "brest", short: "BRT", league: "Ligue_1", stadium: "Stade Francis-Le Blé", strength: 70 },
    { name: "LOSC Lille", id: "lille", short: "LIL", league: "Ligue_1", stadium: "Stade Pierre-Mauroy", strength: 75 },
    { name: "OGC Nice", id: "nice", short: "NCE", league: "Ligue_1", stadium: "Allianz Riviera", strength: 72 },
    { name: "Olympique Lyonnais", id: "lyon", short: "OL", league: "Ligue_1", stadium: "Groupama Stadium", strength: 78 },
    { name: "RC Lens", id: "lens", short: "LEN", league: "Ligue_1", stadium: "Stade Bollaert-Delelis", strength: 76 },
    { name: "Olympique de Marseille", id: "marseille", short: "OM", league: "Ligue_1", stadium: "Stade Vélodrome", strength: 82 },
    { name: "Stade de Reims", id: "reims", short: "REI", league: "Ligue_1", stadium: "Stade Auguste-Delaune", strength: 69 },
    { name: "Stade Rennais FC", id: "rennes", short: "REN", league: "Ligue_1", stadium: "Roazhon Park", strength: 74 },
    { name: "Toulouse FC", id: "toulouse", short: "TOU", league: "Ligue_1", stadium: "Stadium de Toulouse", strength: 68 },
    { name: "Montpellier HSC", id: "montpellier", short: "MPL", league: "Ligue_1", stadium: "Stade de la Mosson", strength: 66 },
    { name: "RC Strasbourg Alsace", id: "strasbourg", short: "STR", league: "Ligue_1", stadium: "Stade de la Meinau", strength: 70 },
    { name: "FC Nantes", id: "nantes", short: "NAN", league: "Ligue_1", stadium: "Stade de la Beaujoire", strength: 65 },
    { name: "Le Havre AC", id: "le_havre", short: "LHA", league: "Ligue_1", stadium: "Stade Océane", strength: 64 },
    { name: "AJ Auxerre", id: "auxerre", short: "AUX", league: "Ligue_1", stadium: "Stade de l'Abbé-Deschamps", strength: 62 },
    { name: "Angers SCO", id: "angers", short: "ANG", league: "Ligue_1", stadium: "Stade Raymond Kopa", strength: 60 },
    { name: "AS Saint-Étienne", id: "saint_etienne", short: "ASSE", league: "Ligue_1", stadium: "Stade Geoffroy-Guichard", strength: 58 },

    // Ligue_2 Saison 2024/2025

    { name: "Clermont Foot",         id: "clermontfoot",         short: "CLE", league: "Ligue_2", stadium: "Stade Gabriel Montpied",           strength: 75 },
    { name: "FC Lorient",            id: "fclorient",            short: "LOR", league: "Ligue_2", stadium: "Stade du Moustoir",               strength: 76 },
    { name: "FC Metz",               id: "fcmetz",               short: "MET", league: "Ligue_2", stadium: "Stade Saint-Symphorien",         strength: 78 },
    { name: "SC Amiens",             id: "scamiens",             short: "AMI", league: "Ligue_2", stadium: "Stade de la Licorne",             strength: 70 },
    { name: "FC Annecy",             id: "fcannecy",             short: "ANN", league: "Ligue_2", stadium: "Stade de l'Octroi",               strength: 67 },
    { name: "SC Bastia",             id: "scbastia",             short: "BAS", league: "Ligue_2", stadium: "Stade Armand Cesari",            strength: 69 },
    { name: "SM Caen",               id: "smcaen",               short: "CAE", league: "Ligue_2", stadium: "Stade Michel d'Ornano",         strength: 74 },
    { name: "USL Dunkerque",         id: "usldunkerque",         short: "DUN", league: "Ligue_2", stadium: "Stade Marcel-Tribut",            strength: 64 },
    { name: "Grenoble Foot",         id: "grenoblefoot",         short: "GRE", league: "Ligue_2", stadium: "Stade des Alpes",                strength: 71 },
    { name: "EA Guingamp",           id: "eaguingamp",           short: "GUI", league: "Ligue_2", stadium: "Stade de Roudourou",              strength: 72 },
    { name: "Stade Laval",           id: "stadelaval",           short: "LAV", league: "Ligue_2", stadium: "Stade Francis Le Basser",        strength: 66 },
    { name: "Paris FC",              id: "parisfc",              short: "PAR", league: "Ligue_2", stadium: "Stade Charléty",                strength: 74 },
    { name: "FC Pau",                id: "fcpau",                short: "PAU", league: "Ligue_2", stadium: "Stade du Hameau",               strength: 68 },
    { name: "AF Rodez",              id: "afrodez",              short: "ROD", league: "Ligue_2", stadium: "Stade Paul Lignon",             strength: 65 },
    { name: "ES Troyes AC",          id: "estroyes",             short: "TRO", league: "Ligue_2", stadium: "Stade de l'Aube",                strength: 72 },
    { name: "FC Valenciennes",       id: "fcvalenciennes",       short: "FCV", league: "Ligue_2", stadium: "Stade du Hainaut",               strength: 70 },
    { name: "FC Martigues",          id: "fcmartigues",          short: "MAR", league: "Ligue_2", stadium: "Stade Francis Turcan",           strength: 63 },
    { name: "Red Star Paris",        id: "redstarparis",         short: "RED", league: "Ligue_2", stadium: "Stade Bauer",                    strength: 65 },


    //International

    //Fehlende Teams aus der Champions League Saison 2024/2025
    { name: "LOSC Lille", id: "lille", short: "LIL", league: "Champions League", stadium: "Stade Pierre-Mauroy", strength: 75 },
    { name: "Paris Saint-Germain", id: "psg", short: "PSG", league: "Champions League", stadium: "Parc des Princes", strength: 88 },
    { name: "SL Benfica", id: "benfica", short: "BEN", league: "Champions League", stadium: "Estádio da Luz", strength: 80 },
    { name: "AS Monaco", id: "monaco", short: "MON", league: "Champions League", stadium: "Stade Louis II", strength: 76 },
    { name: "Stade Brestois", id: "brest", short: "BRET", league: "Champions League", stadium: "Stade Francis-Le Blé", strength: 72 },
    { name: "Celtic FC", id: "celtic", short: "CEL", league: "Champions League", stadium: "Celtic Park", strength: 73 },
    { name: "Sporting CP", id: "sporting", short: "SPO", league: "Champions League", stadium: "Estádio José Alvalade", strength: 79 },
    { name: "Club Brugge", id: "brugge", short: "BRU", league: "Champions League", stadium: "Jan Breydel Stadion", strength: 71 },
    { name: "Dinamo Zagreb", id: "zagreb", short: "DZG", league: "Champions League", stadium: "Stadion Maksimir", strength: 70 },
    { name: "Shakhtar Donetsk", id: "shaktar", short: "SHK", league: "Champions League", stadium: "Arena Lviv", strength: 74 },
    { name: "Crvena Zvezda", id: "zvezda", short: "ZVE", league: "Champions League", stadium: "Rajko Mitić Stadium", strength: 69 },
    { name: "Sturm Graz", id: "graz", short: "STU", league: "Champions League", stadium: "Merkur Arena", strength: 68 },
    { name: "Sparta Prag", id: "prag", short: "PRA", league: "Champions League", stadium: "Generali Arena", strength: 70 },
    { name: "RB Salzburg", id: "salzburg", short: "RBS", league: "Champions League", stadium: "Red Bull Arena", strength: 72 },
    { name: "Slovan Bratislava", id: "bratislava", short: "SLO", league: "Champions League", stadium: "Tehelné pole", strength: 67 },
    { name: "BSC Young Boys", id: "youngboys", short: "YB", league: "Champions League", stadium: "Wankdorf Stadion", strength: 71 },
    
    //Fehlende Teams aus der Europa League Saison 2024/2025
    { name: "Olympiakos Piräus", id: "olympiakos", short: "OLY", league: "Europa League", stadium: "Georgios Karaiskakis Stadium", strength: 70 },
    { name: "OGC Nizza", id: "ogcnizza", short: "NIC", league: "Europa League", stadium: "Allianz Riviera", strength: 75 },
    { name: "Olympique Lyon", id: "olympiquelyon", short: "LYO", league: "Europa League", stadium: "Groupama Stadium", strength: 78 },
    { name: "FC Porto", id: "fcporto", short: "POR", league: "Europa League", stadium: "Estádio do Dragão", strength: 80 },
    { name: "SC Braga", id: "braga", short: "BRA", league: "Europa League", stadium: "Estádio Municipal de Braga", strength: 75},
    { name: "Union Saint-Gilloise", id: "unionsg", short: "USG", league: "Europa League", stadium: "Stade Joseph Marien", strength: 70 },
    { name: "RSC Anderlecht", id: "anderlecht", short: "AND", league: "Europa League", stadium: "Lotto Park", strength: 71 },
    { name: "Rangers FC", id: "rangers", short: "RAN", league: "Europa League", stadium: "Ibrox Stadium", strength: 76 },
    { name: "Fenerbahçe", id: "fenerbahce", short: "FEN", league: "Europa League", stadium: "Şükrü Saracoğlu Stadium", strength: 72 },
    { name: "Galatasaray", id: "galatasaray", short: "GAL", league: "Europa League", stadium: "RAMS Park", strength: 78 },
    { name: "Beşiktaş", id: "besiktas", short: "BES", league: "Europa League", stadium: "Vodafone Park", strength: 71 },
    { name: "Dynamo Kiew", id: "kiew", short: "KIE", league: "Europa League", stadium: "NSK Olimpijskyj", strength: 75 },
    { name: "Slavia Prag", id: "slaviaprag", short: "SLA", league: "Europa League", stadium: "Eden Arena", strength: 71 },
    { name: "Viktoria Pilsen", id: "viktoriapilsen", short: "VIK", league: "Europa League", stadium: "Doosan Arena", strength: 69 },
    { name: "Bodø/Glimt", id: "bodoglimt", short: "BOD", league: "Europa League", stadium: "Aspmyra Stadion", strength: 72 },
    { name: "FC Midtjylland", id: "midtjylland", short: "MID", league: "Europa League", stadium: "MCH Arena", strength: 71 },
    { name: "PAOK Thessaloniki", id: "paok", short: "PAO", league: "Europa League", stadium: "Toumba Stadium", strength: 73 },
    { name: "Maccabi Tel Aviv", id: "maccabitelaviv", short: "MAC", league: "Europa League", stadium: "Bloomfield Stadium", strength: 68 },
    { name: "Malmö FF", id: "malmo", short: "MFF", league: "Europa League", stadium: "Eleda Stadion", strength: 72 },
    { name: "IF Elfsborg", id: "elfsborg", short: "ELF", league: "Europa League", stadium: "Boras Arena", strength: 69 },
    { name: "Ferencvárosi TC", id: "ferencvaros", short: "FER", league: "Europa League", stadium: "Groupama Aréna", strength: 71 },
    { name: "FCSB", id: "fcsb", short: "FCS", league: "Europa League", stadium: "Arena Națională", strength: 73 },
    { name: "Ludogorets Razgrad", id: "ludogorets", short: "LUD", league: "Europa League", stadium: "Huvepharma Arena", strength: 70 },
    { name: "Qarabag FK", id: "qarabag", short: "QAR", league: "Europa League", stadium: "Tofiq Bahramov Stadium", strength: 77 },
    { name: "FK RFS", id: "fkrfs", short: "RFS", league: "Europa League", stadium: "LNK Sporta Parks", strength: 70 },

    //Fehlende Teams aus der Conference League Saison 2024/2025
    { name: "Panathinaikos", id: "panathinaikos", short: "PAN", league: "Conference League", stadium: "Apostolos Nikolaidis", strength: 72 },
    { name: "FC Kopenhagen", id: "kopenhagen", short: "KOP", league: "Conference League", stadium: "Parken Stadium", strength: 74 },
    { name: "KAA Gent", id: "kaagent", short: "GEN", league: "Conference League", stadium: "Ghelamco Arena", strength: 73 },
    { name: "Cercle Brügge", id: "cerclebrugge", short: "CER", league: "Conference League", stadium: "Jan Breydel Stadion", strength: 74 },
    { name: "Basaksehir", id: "basaksehir", short: "BAS", league: "Conference League", stadium: "Başakşehir Fatih Terim Stadium", strength: 67 },
    { name: "Vitória Guimarães", id: "vitoriaguimaraes", short: "VIT", league: "Conference League", stadium: "Estádio D. Afonso Henriques", strength: 73 },
    { name: "LASK", id: "lask", short: "LASK", league: "Conference League", stadium: "Raiffeisen Arena", strength: 74 },
    { name: "FC Lugano", id: "lugano", short: "LUG", league: "Conference League", stadium: "Stadio di Cornaredo", strength: 72 },
    { name: "Rapid Wien", id: "rapidwien", short: "RAP", league: "Conference League", stadium: "Allianz Stadion", strength: 74 },
    { name: "TSC Bačka Topola", id: "tscbackatopola", short: "TSC", league: "Conference League", stadium: "TSC Arena", strength: 71 },
    { name: "Molde FK", id: "molde", short: "MOL", league: "Conference League", stadium: "Aker Stadion", strength: 74 },
    { name: "Legia Warschau", id: "legia", short: "LEG", league: "Conference League", stadium: "Stadion Wojska Polskiego", strength: 75 },
    { name: "FC St. Gallen", id: "stgallen", short: "STG", league: "Conference League", stadium: "Kybunpark", strength: 72 },
    { name: "Pafos FC", id: "pafos", short: "PAF", league: "Conference League", stadium: "Stelios Kyriakides Stadium", strength: 70 },
    { name: "Heart of Midlothian", id: "hearts", short: "HEA", league: "Conference League", stadium: "Tynecastle Park", strength: 71 },
    { name: "Omonia Nikosia", id: "omonia", short: "OMO", league: "Conference League", stadium: "GSP Stadium", strength: 72 },
    { name: "Djurgårdens IF", id: "djurgardens", short: "DJU", league: "Conference League", stadium: "Tele2 Arena", strength: 73 },
    { name: "Jagiellonia Białystok", id: "jagiellonia", short: "JAG", league: "Conference League", stadium: "Stadion Miejski Białystok", strength: 72 },
    { name: "APOEL Nikosia", id: "apoel", short: "APO", league: "Conference League", stadium: "GSP Stadium", strength: 74 },
    { name: "NK Celje", id: "nkcelje", short: "CEL", league: "Conference League", stadium: "Stadion Z'dežele", strength: 71 },
    { name: "Mladá Boleslav", id: "mladaboleslav", short: "MLA", league: "Conference League", stadium: "Lokotrans Arena", strength: 70 },
    { name: "Olimpija Ljubljana", id: "olimpijaljubljana", short: "OLI", league: "Conference League", stadium: "Stadion Stožice", strength: 72 },
    { name: "FC Astana", id: "astana", short: "AST", league: "Conference League", stadium: "Astana Arena", strength: 70 },
    { name: "FC Noah", id: "noah", short: "NOA", league: "Conference League", stadium: "Nairi Stadium", strength: 69 },
    { name: "HJK Helsinki", id: "hjk", short: "HJK", league: "Conference League", stadium: "Bolt Arena", strength: 73 },
    { name: "FK Borac Banja Luka", id: "borac", short: "BOR", league: "Conference League", stadium: "Gradski stadion Banja Luka", strength: 69 },
    { name: "Dinamo Minsk", id: "dinamominsk", short: "DIN", league: "Conference League", stadium: "Dinamo Stadion", strength: 71 },
    { name: "Petrocub Hîncești", id: "petrocub", short: "PET", league: "Conference League", stadium: "Stadionul Zimbru", strength: 68 },
    { name: "Shamrock Rovers", id: "shamrock", short: "SHR", league: "Conference League", stadium: "Tallaght Stadium", strength: 70 },
    { name: "Larne FC", id: "larne", short: "LAR", league: "Conference League", stadium: "Inver Park", strength: 67 },
    { name: "Víkingur Reykjavík", id: "vikingur", short: "VIK", league: "Conference League", stadium: "Víkingsvöllur", strength: 67 },
    { name: "The New Saints", id: "newsaints", short: "TNS", league: "Conference League", stadium: "Park Hall", strength: 66 }
    
    
];